### ISSUE TITLE
Change `json-20090211_1` dependency to work on Java 9

### ISSUE THREAD

**Issue by sharpTrick** [FasterXML/jackson-datatype-json-org#12]
I get this is the wrong place. But I could not find the home for geronimo bundles. Is far as I can tell is is dead.

However in my attempts to modularize my quandl library which depends on com.jimmoores:quandl-core which in turn depends on this somehow, I discovered that the automatic module naming algorithm fails to name the json-2090211_1 with a valid module name.

I have found that if the line 'Automatic-Module-Name: org.json' is added to the MANIFEST.MF in the META-INF within the json-20090211_1.jar then my library compiles.

FYI...

**Comment by cowtowncoder** [comment]
Ok. So... since org.json is a dependency, and as per comment at some point this artifact has been one (of only?) variants with OSGi info, I guess it might be worth another look to see if we could do better.

Looking at this:

http://mvnrepository.com/artifact/org.json/json/20171018

I _think_ it does have basic OSGi metadata. I could change dependency to that one (seems like a good idea in general) if that would help? This assuming it's the underscore that causes issues, and not lack 3-part "full" version number.

About the only concern here, I think (aside from OSGi metadata being broken but I assume it's not) would be change in dependencies for patch release (2.9.4).

**Comment by sharpTrick** [comment]
I would wager that you are correct with the underscore hypothesis.

**Comment by cowtowncoder** [comment]
Ok. So how about I'll just change the dependency in `2.9` (and `master`) and it should not at least hurt.

**Comment by jimmoores** [comment]
Many thanks for the fix. Any ETA on 2.9.4?

**Comment by cowtowncoder** [comment]
I think the best approximation I can give is "before end of January". Hoping to clear couple of issues with `jackson-databind` still.
